apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app-1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-app-1

  project: default
  source:
    repoURL: https://github.com/josephoyomikavala/manifest-repo.git
    targetRevision: HEAD
    path: source

  syncPolicy:
    syncOptions:
      - CreateNamespace=true # create namespace on the fly

    automated:
      selfHeal: true # negate manual kubectl commands
      prune: true
