apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bank-of-anthos
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: bank-of-anthos

  project: default
  source:
    repoURL: https://github.com/josephoyomikavala/bank-of-anthos.git
    targetRevision: HEAD
    path: apps

  syncPolicy:
    syncOptions:
      - CreateNamespace=true # create namespace on the fly

    automated:
      selfHeal: true # negate manual kubectl commands
      prune: true
